defaults: &defaults
  username: postgres
  adapter: postgres

development:
  database: vulcan_development
  <<: *defaults
test:
  database: vulcan_test
  <<: *defaults
production:
  database: vulcan_production
  <<: *defaults
